### ISSUE TITLE
Nox tests-3.9 fail: ModuleNotFoundError: No module named 'django'

### ISSUE THREAD

**Issue by kevinbowen777** [kevinbowen777/django-start#101]
All other 3.9 Nox tests pass successfully. Here is the traceback:
```
Traceback (most recent call last):
  File "/home/kbowen/dev/python/repos/django/django-start/.nox/tests-3-9/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "/home/kbowen/dev/python/repos/django/django-start/.nox/tests-3-9/lib/python3.9/site-packages/_pytest/config/__init__.py", line 190, in console_main
    code = main()
  File "/home/kbowen/dev/python/repos/django/django-start/.nox/tests-3-9/lib/python3.9/site-packages/_pytest/config/__init__.py", line 148, in main
    config = _prepareconfig(args, plugins)
  File "/home/kbowen/dev/python/repos/django/django-start/.nox/tests-3-9/lib/python3.9/site-packages/_pytest/config/__init__.py", line 329, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "/home/kbowen/dev/python/repos/django/django-start/.nox/tests-3-9/lib/python3.9/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/home/kbowen/dev/python/repos/django/django-start/.nox/tests-3-9/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/home/kbowen/dev/python/repos/django/django-start/.nox/tests-3-9/lib/python3.9/site-packages/pluggy/_callers.py", line 55, in _multicall
    gen.send(outcome)
  File "/home/kbowen/dev/python/repos/django/django-start/.nox/tests-3-9/lib/python3.9/site-packages/_pytest/helpconfig.py", line 103, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "/home/kbowen/dev/python/repos/django/django-start/.nox/tests-3-9/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/kbowen/dev/python/repos/django/django-start/.nox/tests-3-9/lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/home/kbowen/dev/python/repos/django/django-start/.nox/tests-3-9/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1058, in pytest_cmdline_parse
    self.parse(args)
  File "/home/kbowen/dev/python/repos/django/django-start/.nox/tests-3-9/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1346, in parse
    self._preparse(args, addopts=addopts)
  File "/home/kbowen/dev/python/repos/django/django-start/.nox/tests-3-9/lib/python3.9/site-packages/_pytest/config/__init__.py", line 1248, in _preparse
    self.hook.pytest_load_initial_conftests(
  File "/home/kbowen/dev/python/repos/django/django-start/.nox/tests-3-9/lib/python3.9/site-packages/pluggy/_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "/home/kbowen/dev/python/repos/django/django-start/.nox/tests-3-9/lib/python3.9/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/home/kbowen/dev/python/repos/django/django-start/.nox/tests-3-9/lib/python3.9/site-packages/pluggy/_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "/home/kbowen/dev/python/repos/django/django-start/.nox/tests-3-9/lib/python3.9/site-packages/pluggy/_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/kbowen/dev/python/repos/django/django-start/.nox/tests-3-9/lib/python3.9/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "/home/kbowen/dev/python/repos/django/django-start/.nox/tests-3-9/lib/python3.9/site-packages/pytest_cov/plugin.py", line 152, in pytest_load_initial_conftests
    plugin = CovPlugin(options, early_config.pluginmanager)
  File "/home/kbowen/dev/python/repos/django/django-start/.nox/tests-3-9/lib/python3.9/site-packages/pytest_cov/plugin.py", line 203, in __init__
    self.start(engine.Central)
  File "/home/kbowen/dev/python/repos/django/django-start/.nox/tests-3-9/lib/python3.9/site-packages/pytest_cov/plugin.py", line 225, in start
    self.cov_controller.start()
  File "/home/kbowen/dev/python/repos/django/django-start/.nox/tests-3-9/lib/python3.9/site-packages/pytest_cov/engine.py", line 44, in ensure_topdir_wrapper
    return meth(self, *args, **kwargs)
  File "/home/kbowen/dev/python/repos/django/django-start/.nox/tests-3-9/lib/python3.9/site-packages/pytest_cov/engine.py", line 233, in start
    self.cov.erase()
  File "/home/kbowen/dev/python/repos/django/django-start/.nox/tests-3-9/lib/python3.9/site-packages/coverage/control.py", line 631, in erase
    self._init()
  File "/home/kbowen/dev/python/repos/django/django-start/.nox/tests-3-9/lib/python3.9/site-packages/coverage/control.py", line 293, in _init
    self._plugins = Plugins.load_plugins(self.config.plugins, self.config, self._debug)
  File "/home/kbowen/dev/python/repos/django/django-start/.nox/tests-3-9/lib/python3.9/site-packages/coverage/plugin_support.py", line 42, in load_plugins
    __import__(module)
  File "/home/kbowen/dev/python/repos/django/django-start/.nox/tests-3-9/lib/python3.9/site-packages/django_coverage_plugin/__init__.py", line 6, in <module>
    from .plugin import DjangoTemplatePluginException  # noqa
  File "/home/kbowen/dev/python/repos/django/django-start/.nox/tests-3-9/lib/python3.9/site-packages/django_coverage_plugin/plugin.py", line 17, in <module>
    import django
ModuleNotFoundError: No module named 'django'
```

**Comment by kevinbowen777** [comment]
Django 5.0 is dropping support for Python 3.9. Closing issue.
